/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'nature' : null } |
  { 'history' : null } |
  { 'technology' : null } |
  { 'geography' : null } |
  { 'science' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface FunFact {
  'title' : string,
  'description' : string,
  'category' : Category,
}
export interface TriviaQuestion {
  'question' : string,
  'difficulty' : Difficulty,
  'correctAnswerIndex' : bigint,
  'category' : Category,
  'timesAttempted' : bigint,
  'options' : Array<string>,
}
export interface _SERVICE {
  'addFunFact' : ActorMethod<[string, string, Category], bigint>,
  'addTriviaQuestion' : ActorMethod<
    [string, Array<string>, bigint, Category, Difficulty],
    bigint
  >,
  'getAllFunFacts' : ActorMethod<[], Array<FunFact>>,
  'getAllQuestions' : ActorMethod<[], Array<TriviaQuestion>>,
  'getAllQuestionsNoAnswers' : ActorMethod<[], Array<TriviaQuestion>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getDailyTrivia' : ActorMethod<[], [] | [TriviaQuestion]>,
  'getDifficulties' : ActorMethod<[], Array<string>>,
  'getFunFact' : ActorMethod<[bigint], FunFact>,
  'getFunFactsByCategory' : ActorMethod<[Category], Array<FunFact>>,
  'getQuestionsByCategory' : ActorMethod<[Category], Array<TriviaQuestion>>,
  'getQuestionsByDifficulty' : ActorMethod<[Difficulty], Array<TriviaQuestion>>,
  'getRandomFunFact' : ActorMethod<[], [] | [FunFact]>,
  'getTotalFunFactsCount' : ActorMethod<[], bigint>,
  'getTotalQuestionsCount' : ActorMethod<[], bigint>,
  'getTrivia' : ActorMethod<[bigint], TriviaQuestion>,
  'incrementQuestionAttempts' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];