/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'nature' : IDL.Null,
  'history' : IDL.Null,
  'technology' : IDL.Null,
  'geography' : IDL.Null,
  'science' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const FunFact = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
});
export const TriviaQuestion = IDL.Record({
  'question' : IDL.Text,
  'difficulty' : Difficulty,
  'correctAnswerIndex' : IDL.Nat,
  'category' : Category,
  'timesAttempted' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addFunFact' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'addTriviaQuestion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Category, Difficulty],
      [IDL.Nat],
      [],
    ),
  'getAllFunFacts' : IDL.Func([], [IDL.Vec(FunFact)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(TriviaQuestion)], ['query']),
  'getAllQuestionsNoAnswers' : IDL.Func(
      [],
      [IDL.Vec(TriviaQuestion)],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDailyTrivia' : IDL.Func([], [IDL.Opt(TriviaQuestion)], ['query']),
  'getDifficulties' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFunFact' : IDL.Func([IDL.Nat], [FunFact], ['query']),
  'getFunFactsByCategory' : IDL.Func([Category], [IDL.Vec(FunFact)], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(TriviaQuestion)],
      ['query'],
    ),
  'getQuestionsByDifficulty' : IDL.Func(
      [Difficulty],
      [IDL.Vec(TriviaQuestion)],
      ['query'],
    ),
  'getRandomFunFact' : IDL.Func([], [IDL.Opt(FunFact)], ['query']),
  'getTotalFunFactsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalQuestionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrivia' : IDL.Func([IDL.Nat], [TriviaQuestion], ['query']),
  'incrementQuestionAttempts' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'nature' : IDL.Null,
    'history' : IDL.Null,
    'technology' : IDL.Null,
    'geography' : IDL.Null,
    'science' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FunFact = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
  });
  const TriviaQuestion = IDL.Record({
    'question' : IDL.Text,
    'difficulty' : Difficulty,
    'correctAnswerIndex' : IDL.Nat,
    'category' : Category,
    'timesAttempted' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addFunFact' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'addTriviaQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Category, Difficulty],
        [IDL.Nat],
        [],
      ),
    'getAllFunFacts' : IDL.Func([], [IDL.Vec(FunFact)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(TriviaQuestion)], ['query']),
    'getAllQuestionsNoAnswers' : IDL.Func(
        [],
        [IDL.Vec(TriviaQuestion)],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDailyTrivia' : IDL.Func([], [IDL.Opt(TriviaQuestion)], ['query']),
    'getDifficulties' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFunFact' : IDL.Func([IDL.Nat], [FunFact], ['query']),
    'getFunFactsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(FunFact)],
        ['query'],
      ),
    'getQuestionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(TriviaQuestion)],
        ['query'],
      ),
    'getQuestionsByDifficulty' : IDL.Func(
        [Difficulty],
        [IDL.Vec(TriviaQuestion)],
        ['query'],
      ),
    'getRandomFunFact' : IDL.Func([], [IDL.Opt(FunFact)], ['query']),
    'getTotalFunFactsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalQuestionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrivia' : IDL.Func([IDL.Nat], [TriviaQuestion], ['query']),
    'incrementQuestionAttempts' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };