/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FunFact {
    title: string;
    description: string;
    category: Category;
}
export interface TriviaQuestion {
    question: string;
    difficulty: Difficulty;
    correctAnswerIndex: bigint;
    category: Category;
    timesAttempted: bigint;
    options: Array<string>;
}
export enum Category {
    nature = "nature",
    history = "history",
    technology = "technology",
    geography = "geography",
    science = "science"
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export interface backendInterface {
    addFunFact(title: string, description: string, category: Category): Promise<bigint>;
    addTriviaQuestion(question: string, options: Array<string>, correctAnswerIndex: bigint, category: Category, difficulty: Difficulty): Promise<bigint>;
    getAllFunFacts(): Promise<Array<FunFact>>;
    getAllQuestions(): Promise<Array<TriviaQuestion>>;
    getAllQuestionsNoAnswers(): Promise<Array<TriviaQuestion>>;
    getCategories(): Promise<Array<string>>;
    getDailyTrivia(): Promise<TriviaQuestion | null>;
    getDifficulties(): Promise<Array<string>>;
    getFunFact(id: bigint): Promise<FunFact>;
    getFunFactsByCategory(category: Category): Promise<Array<FunFact>>;
    getQuestionsByCategory(category: Category): Promise<Array<TriviaQuestion>>;
    getQuestionsByDifficulty(difficulty: Difficulty): Promise<Array<TriviaQuestion>>;
    getRandomFunFact(): Promise<FunFact | null>;
    getTotalFunFactsCount(): Promise<bigint>;
    getTotalQuestionsCount(): Promise<bigint>;
    getTrivia(id: bigint): Promise<TriviaQuestion>;
    incrementQuestionAttempts(id: bigint): Promise<void>;
}
import type { Category as _Category, Difficulty as _Difficulty, FunFact as _FunFact, TriviaQuestion as _TriviaQuestion } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFunFact(arg0: string, arg1: string, arg2: Category): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFunFact(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFunFact(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addTriviaQuestion(arg0: string, arg1: Array<string>, arg2: bigint, arg3: Category, arg4: Difficulty): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTriviaQuestion(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTriviaQuestion(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllFunFacts(): Promise<Array<FunFact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFunFacts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFunFacts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuestions(): Promise<Array<TriviaQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuestionsNoAnswers(): Promise<Array<TriviaQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestionsNoAnswers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestionsNoAnswers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getDailyTrivia(): Promise<TriviaQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTrivia();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTrivia();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDifficulties(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDifficulties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDifficulties();
            return result;
        }
    }
    async getFunFact(arg0: bigint): Promise<FunFact> {
        if (this.processError) {
            try {
                const result = await this.actor.getFunFact(arg0);
                return from_candid_FunFact_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFunFact(arg0);
            return from_candid_FunFact_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFunFactsByCategory(arg0: Category): Promise<Array<FunFact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFunFactsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFunFactsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByCategory(arg0: Category): Promise<Array<TriviaQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByDifficulty(arg0: Difficulty): Promise<Array<TriviaQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByDifficulty(to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByDifficulty(to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomFunFact(): Promise<FunFact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomFunFact();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomFunFact();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalFunFactsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFunFactsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFunFactsCount();
            return result;
        }
    }
    async getTotalQuestionsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalQuestionsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalQuestionsCount();
            return result;
        }
    }
    async getTrivia(arg0: bigint): Promise<TriviaQuestion> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrivia(arg0);
                return from_candid_TriviaQuestion_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrivia(arg0);
            return from_candid_TriviaQuestion_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementQuestionAttempts(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementQuestionAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementQuestionAttempts(arg0);
            return result;
        }
    }
}
function from_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_FunFact_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FunFact): FunFact {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TriviaQuestion_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TriviaQuestion): TriviaQuestion {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TriviaQuestion]): TriviaQuestion | null {
    return value.length === 0 ? null : from_candid_TriviaQuestion_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FunFact]): FunFact | null {
    return value.length === 0 ? null : from_candid_FunFact_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: string;
    difficulty: _Difficulty;
    correctAnswerIndex: bigint;
    category: _Category;
    timesAttempted: bigint;
    options: Array<string>;
}): {
    question: string;
    difficulty: Difficulty;
    correctAnswerIndex: bigint;
    category: Category;
    timesAttempted: bigint;
    options: Array<string>;
} {
    return {
        question: value.question,
        difficulty: from_candid_Difficulty_n13(_uploadFile, _downloadFile, value.difficulty),
        correctAnswerIndex: value.correctAnswerIndex,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category),
        timesAttempted: value.timesAttempted,
        options: value.options
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    category: _Category;
}): {
    title: string;
    description: string;
    category: Category;
} {
    return {
        title: value.title,
        description: value.description,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nature: null;
} | {
    history: null;
} | {
    technology: null;
} | {
    geography: null;
} | {
    science: null;
}): Category {
    return "nature" in value ? Category.nature : "history" in value ? Category.history : "technology" in value ? Category.technology : "geography" in value ? Category.geography : "science" in value ? Category.science : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TriviaQuestion>): Array<TriviaQuestion> {
    return value.map((x)=>from_candid_TriviaQuestion_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FunFact>): Array<FunFact> {
    return value.map((x)=>from_candid_FunFact_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    nature: null;
} | {
    history: null;
} | {
    technology: null;
} | {
    geography: null;
} | {
    science: null;
} {
    return value == Category.nature ? {
        nature: null
    } : value == Category.history ? {
        history: null
    } : value == Category.technology ? {
        technology: null
    } : value == Category.geography ? {
        geography: null
    } : value == Category.science ? {
        science: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
